CREATE TABLE `users` (
	`USR_ID` VARCHAR(15) NOT NULL COMMENT '사용자아이디',
	`PASSWORD` VARCHAR(20) NULL DEFAULT NULL COMMENT '비밀번호',
	`USR_NM` VARCHAR(20) NULL DEFAULT NULL COMMENT '사용자명',
	`PHONE1_1` VARCHAR(5) NULL DEFAULT NULL COMMENT '연락처1_1',
	`PHONE1_2` VARCHAR(5) NULL DEFAULT NULL COMMENT '연락처1_2',
	`PHONE1_3` VARCHAR(5) NULL DEFAULT NULL COMMENT '연락처1_3',
	`EMAIL` VARCHAR(50) NULL DEFAULT NULL COMMENT '이메일',
	`WRTR` VARCHAR(15) NULL DEFAULT NULL COMMENT '작성자',
	`UPDTR` VARCHAR(15) NULL DEFAULT NULL COMMENT '수정자',
	`WRT_DT` TIMESTAMP NULL DEFAULT NULL COMMENT '작성일시',
	`UPD_DT` TIMESTAMP NULL DEFAULT NULL COMMENT '수정일시',
	PRIMARY KEY (`USR_ID`)
)
COMMENT='사용자정보'
COLLATE='utf8_general_ci'
ENGINE=InnoDB;
